Algoritmo "conversorDeDolar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Converter real para dolar e mostrar se tem dinheiro suficiente para fazer compras
// Data atual  : 21/03/2019
Var
   dolares, reais: real


Inicio
      escreva("Quantos reais você tem: ")
      leia(reais)
      dolares <- reais / 3.79
      escreva("Eu posso ter: U$", dolares)

      


Fimalgoritmo