Algoritmo "exemplodefuncaoaritmetica"
// Disciplina   : [Linguagem e Lógica de Programação]
// Data atual  : 20/03/2019
Var
// Seção de Declarações das variáveis 
   a, b: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a <- raizq(90)
   escreval("Raiz de 90: ", a)
   escreval("Raiz inteira de 90: ", int(a))

   b <- grauprad(90)
   escreval("Converter 90º para radiano da: ", b, " rad")
   escreval("O seno de 90º é: ", sen(b))



Fimalgoritmo