Algoritmo "idade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Dizer quantos anos tem a Creuza!
// Data atual  : 21/03/2019
Var
   anoAtual, nascimento, idade: inteiro


Inicio
      escreval("Em que anos nós estamos: ")
      leia(anoAtual)
      escreval("Em que ano eu nasci: ")
      leia(nascimento)
      idade <- anoAtual - nascimento
      escreva("A minha idade é ", idade, " anos!")


Fimalgoritmo